import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import dbConnect from './lib/dbConnect.js';
import productRoutes from './routes/productRoutes.js';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
dbConnect().catch(e=>{console.error('DB connect failed', e); process.exit(1);});
app.use('/api/products', productRoutes);
app.get('/api/health', (_req,res)=>res.json({ ok:true }));
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log(`Backend running on http://localhost:${PORT}`));
